document.addEventListener('DOMContentLoaded', () => {
    const topicInput = document.getElementById('topicInput');
    const generateIdeasBtn = document.getElementById('generateIdeasBtn');
    const ideaOutput = document.getElementById('ideaOutput');

    // Simulate an AI/LLM response
    const generateCreativeIdeas = (topic) => {
        const lowerTopic = topic.toLowerCase();
        const ideas = [];

        // General creative prompts
        ideas.push(`Imagine a world where '${topic}' is no longer a problem. What does it look like?`);
        ideas.push(`How can we combine '${topic}' with an unexpected element, like 'space travel' or 'ancient philosophy'?`);
        ideas.push(`What if we reversed the typical approach to '${topic}'? What would be the opposite solution?`);
        ideas.push(`Explore '${topic}' from the perspective of a child, an alien, or an animal. What unique insights emerge?`);
        ideas.push(`Brainstorm 5 radical, perhaps impractical, ideas for '${topic}'. Then try to make one practical.`);

        // More specific variations based on common keywords
        if (lowerTopic.includes('food') || lowerTopic.includes('restaurant')) {
            ideas.push(`A restaurant concept where dishes are generated by AI based on your mood and dietary needs.`);
            ideas.push(`Edible packaging for all food products related to '${topic}'.`);
        }
        if (lowerTopic.includes('education') || lowerTopic.includes('learning')) {
            ideas.push(`Personalized learning paths for '${topic}' that adapt in real-time using biometric feedback.`);
            ideas.push(`A gamified platform for '${topic}' where learning is a collaborative adventure.`);
        }
        if (lowerTopic.includes('transport') || lowerTopic.includes('travel')) {
            ideas.push(`A hyperloop system designed specifically for recreational travel within '${topic}' areas.`);
            ideas.push(`Personalized drone taxis for individual travel, optimized for scenic routes related to '${topic}'.`);
        }
        if (lowerTopic.includes('home') || lowerTopic.includes('living')) {
            ideas.push(`Modular, self-assembling homes that adapt to your evolving needs and location, focusing on '${topic}'.`);
            ideas.push(`Smart home systems that anticipate your needs based on predictive AI, particularly for '${topic}'.`);
        }
        if (lowerTopic.includes('art') || lowerTopic.includes('design')) {
            ideas.push(`AI-generated art installations that react to viewer emotions concerning '${topic}'.`);
            ideas.push(`Interactive public art that allows citizens to collectively design urban spaces for '${topic}'.`);
        }
        if (lowerTopic.includes('health') || lowerTopic.includes('wellness')) {
            ideas.push(`Wearable tech that provides real-time mental health support tailored to '${topic}'-related stress.`);
            ideas.push(`Personalized nutrition plans delivered via drone, based on your unique microbiome for '${topic}'.`);
        }
        if (lowerTopic.includes('environment') || lowerTopic.includes('sustainab')) {
            ideas.push(`Self-repairing infrastructure for '${topic}' that uses bio-engineered materials.`);
            ideas.push(`Community-driven micro-grids for energy, powered by local sustainable sources for '${topic}'.`);
        }

        // Shuffle and take a few random ones
        const shuffledIdeas = ideas.sort(() => 0.5 - Math.random());
        return shuffledIdeas.slice(0, Math.floor(Math.random() * 3) + 3); // Return 3 to 5 ideas
    };

    generateIdeasBtn.addEventListener('click', () => {
        const topic = topicInput.value.trim();

        if (topic === '') {
            ideaOutput.innerHTML = '<p class="placeholder-text" style="color: red;">Please enter a topic to generate ideas.</p>';
            return;
        }

        // Display loading state
        ideaOutput.innerHTML = '<p class="loading-text">Generating brilliant ideas for you... Please wait.</p>';
        generateIdeasBtn.disabled = true;

        // Simulate API call with a delay
        setTimeout(() => {
            const generatedIdeas = generateCreativeIdeas(topic);
            
            if (generatedIdeas.length === 0) {
                ideaOutput.innerHTML = '<p class="placeholder-text">Could not generate specific ideas for this topic, try broadening it!</p>';
            } else {
                ideaOutput.innerHTML = generatedIdeas.map(idea => `<p>${idea}</p>`).join('');
            }
            generateIdeasBtn.disabled = false;
        }, 1500); // Simulate network delay
    });
});
