document.addEventListener('DOMContentLoaded', () => {
    const codeInput = document.getElementById('codeInput');
    const refactorBtn = document.getElementById('refactorBtn');
    const outputCodeContainer = document.querySelector('#outputCode code');

    refactorBtn.addEventListener('click', () => {
        const originalCode = codeInput.value.trim();

        if (originalCode === '') {
            outputCodeContainer.textContent = '// Please paste some code to refactor and optimize.';
            return;
        }

        const refactoredCode = simulateAIRefactor(originalCode);
        outputCodeContainer.textContent = refactoredCode;
    });

    /**
     * Simulates an AI code refactoring and optimization process.
     * This is a mock function and provides basic, rule-based suggestions for JavaScript.
     * @param {string} code The input code snippet.
     * @returns {string} The simulated refactored/optimized code.
     */
    function simulateAIRefactor(code) {
        let lines = code.split('\n');
        let refactoredLines = [];
        let suggestions = new Set(); // Use a Set to store unique suggestions

        // Add a header
        refactoredLines.push('// AI Refactored & Optimized Code:');
        refactoredLines.push('// This code has been analyzed by the AI Assistant.');
        refactoredLines.push('');

        lines.forEach(line => {
            let processedLine = line;

            // Rule 1: Replace 'var' with 'let' or 'const'
            if (line.match(/\bvar\s+\w+/)) { // Regex to match 'var' followed by a variable name
                processedLine = processedLine.replace(/\bvar\s+/g, 'let ');
                suggestions.add('// AI SUGGESTION: Consider using `let` or `const` instead of `var` for block-scoping and better variable management.');
            }

            // Rule 2: Suggest arrow functions for traditional function declarations
            // Basic detection: checks for 'function name(...)' pattern, ignoring arrow functions and comments
            if (line.match(/\bfunction\s+\w*\s*\(/) && !line.includes('=>') && !line.trim().startsWith('//')) {
                suggestions.add('// AI SUGGESTION: For concise functions or methods, consider using arrow function syntax `() => {}`.');
            }

            // Rule 3: Suggest removing console.log in production
            if (line.includes('console.log(')) {
                suggestions.add('// AI SUGGESTION: Remove `console.log` statements in production code for improved performance and security.');
            }
            
            // Rule 4: Suggest using template literals instead of string concatenation
            if (line.includes('+') && line.includes('"') && line.includes('$')) { // Simple heuristic
                suggestions.add('// AI SUGGESTION: Use template literals (``) for easier string interpolation instead of concatenation (+).');
            }

            // Rule 5: Suggest destructuring for object/array property access
            if (line.match(/\bconst\s+\w+\s*=\s*\w+\.\w+/)) { // e.g., const name = obj.name;
                suggestions.add('// AI SUGGESTION: Consider using object/array destructuring for cleaner variable assignments.');
            }

            // Add the (potentially processed) line to the refactored output
            refactoredLines.push(processedLine);
        });

        // Add unique suggestions at the end
        if (suggestions.size > 0) {
            refactoredLines.push(''); // Add a new line for separation
            refactoredLines.push('// --- AI Optimization Suggestions ---');
            suggestions.forEach(sug => refactoredLines.push(sug));
            refactoredLines.push('');
        }
        
        refactoredLines.push('// Further optimizations and deeper refactoring may be possible with a more advanced AI.');
        refactoredLines.push('// Generated by AI Code Refactor & Optimization Assistant.');

        return refactoredLines.join('\n');
    }
});
